Repository sanjyotagureddy/dotnet-ecommerce, pull requests merged in 2024-08, with the labels that each got.

#6 BZ-8: refactor: Add projects for Product, move User tests, Update Docker-compose
  aspire/dotnet-ecommerce.AppHost/Program.cs
  aspire/dotnet-ecommerce.AppHost/dotnet-ecommerce.AppHost.csproj
  docker-compose.override.yml
  docker-compose.yml
  dotnet-ecommerce.sln
  src/Product/BelleZone.Product.Api/BelleZone.Product.Api.csproj
  src/Product/BelleZone.Product.Api/BelleZone.Product.Api.http
  src/Product/BelleZone.Product.Api/Controllers/WeatherForecastController.cs
  src/Product/BelleZone.Product.Api/Dockerfile
  src/Product/BelleZone.Product.Api/Program.cs
  src/Product/BelleZone.Product.Api/Properties/launchSettings.json
  src/Product/BelleZone.Product.Api/WeatherForecast.cs
  src/Product/BelleZone.Product.Api/appsettings.Development.json
  src/Product/BelleZone.Product.Api/appsettings.json
  src/Product/BelleZone.Product.Models/BelleZone.Product.Models.csproj
  src/Product/BelleZone.Product.Models/Product.cs
  src/Product/BelleZone.Product.Service/BelleZone.Product.Services.csproj
  src/Product/BelleZone.Product.Service/ProductService.cs
  tests/UnitTests/Product/BelleZone.Product.Api.Tests/BelleZone.Product.Api.Tests.csproj
  tests/UnitTests/Product/BelleZone.Product.Api.Tests/UnitTest1.cs
  tests/UnitTests/Product/BelleZone.Product.Services.Tests/BelleZone.Product.Services.Tests.csproj
  tests/UnitTests/Product/BelleZone.Product.Services.Tests/UnitTest1.cs
  tests/UnitTests/User/BelleZone.User.Api.UnitTests/BelleZone.User.Api.UnitTests.csproj
  tests/UnitTests/User/BelleZone.User.Api.UnitTests/UnitTest1.cs
Labels: enhancement

#7 BZ-3: feat-Added Global Error handling
  NugetListUpdater.bat
  docker-compose.override.yml
  docker-compose.yml
  dotnet-ecommerce.sln
  shared/BelleZone.Shared.Common.Logging/BelleZone.Shared.Common.Logging.csproj
  shared/BelleZone.Shared.Common.Logging/Exceptions/BaseAppException.cs
  shared/BelleZone.Shared.Common.WebApi/AppExtensions.cs
  shared/BelleZone.Shared.Common.WebApi/BelleZone.Shared.Common.WebApi.csproj
  shared/BelleZone.Shared.Common.WebApi/Middlewares/ErrorHandlingMiddleware.cs
  shared/BelleZone.User.Shared.Common/BelleZone.User.Shared.Common.csproj
  src/User/BelleZone.User.Api/BelleZone.User.Api.csproj
  src/User/BelleZone.User.Api/Controllers/WeatherForecastController.cs
  src/User/BelleZone.User.Api/Product.cs
  src/User/BelleZone.User.Api/Program.cs
  util/NugetListUpdater.bat
Labels: enhancement

#15 MS-9: Renaming projects to MeraStore
  .github/workflows/tag-on-merge.yml
  docker-compose.override.yml
  docker-compose.yml
  src/Product/MeraStore.Product.Api/Dockerfile
  src/User/MeraStore.User.Api/Dockerfile
Labels: refactor

#18 MSEC-22: (chore) Added Common Logging Services
  .github/pull_request_template.md
  GitCommit_Nomanclature.md
  aspire/dotnet-ecommerce.AppHost/dotnet-ecommerce.AppHost.csproj
  aspire/dotnet-ecommerce.ServiceDefaults/dotnet-ecommerce.ServiceDefaults.csproj
  docker-compose.override.yml
  kibana/app-logs.ndjson
  shared/MeraStore.Shared.Common.Logging/LoggingExtension.cs
  shared/MeraStore.Shared.Common.Logging/MeraStore.Shared.Common.Logging.csproj
  shared/MeraStore.Shared.Common.WebApi/AppExtensions.cs
  shared/MeraStore.Shared.Common.WebApi/MeraStore.Shared.Common.WebApi.csproj
  shared/MeraStore.Shared.Common.WebApi/Middlewares/CorrelationIdMiddleware.cs
  shared/MeraStore.User.Shared.Common/Constants.cs
  src/Product/MeraStore.Product.Api/MeraStore.Product.Api.csproj
  src/Product/MeraStore.Product.Api/Program.cs
  src/Product/MeraStore.Product.Api/appsettings.json
  src/User/MeraStore.User.Api/MeraStore.User.Api.csproj
  src/User/MeraStore.User.Api/Program.cs
  src/User/MeraStore.User.Api/appsettings.json
  tests/UnitTests/Product/MeraStore.Product.Api.Tests/MeraStore.Product.Api.Tests.csproj
  tests/UnitTests/Product/MeraStore.Product.Services.Tests/MeraStore.Product.Services.Tests.csproj
  tests/UnitTests/User/MeraStore.User.Api.UnitTests/MeraStore.User.Api.UnitTests.csproj
Labels: enhancement

#24 MSEC-27: Fix indexing issue for elastic search and kibana
  docker-compose.override.yml
  docker-compose.yml
  shared/MeraStore.Shared.Common.Logging/LoggingExtension.cs
  shared/MeraStore.Shared.Common.WebApi/Middlewares/RequestResponseLoggingMiddleware.cs
  src/Product/MeraStore.Product.Api/appsettings.json
  src/User/MeraStore.User.Api/Controllers/WeatherForecastController.cs
  src/User/MeraStore.User.Api/appsettings.json
Labels: bug

#30 MSEC-29: feat - Create SharedKernel for Http Client
  dotnet-ecommerce.sln
  shared/MeraStore.Shared.Common.Http/ApiCallerExtensions.cs
  shared/MeraStore.Shared.Common.Http/ApiClient.cs
  shared/MeraStore.Shared.Common.Http/ApiResponse.cs
  shared/MeraStore.Shared.Common.Http/Extensions/HttpResponseExtensions.cs
  shared/MeraStore.Shared.Common.Http/HttpRequestBuilder.cs
  shared/MeraStore.Shared.Common.Http/IApiClient.cs
  shared/MeraStore.Shared.Common.Http/MeraStore.Shared.Common.Http.csproj
  shared/MeraStore.Shared.Common.Http/README.md
  shared/MeraStore.Shared.Common.Logging/Enrichers/IpAddressEnricher.cs
  shared/MeraStore.User.Shared.Common/Constants.cs
  shared/MeraStore.User.Shared.Common/ErrorsCodes/ErrorCodes.cs
  shared/MeraStore.User.Shared.Common/Exceptions/ApiExceptions.cs
  shared/MeraStore.User.Shared.Common/Exceptions/CommonExceptions.cs
  src/Product/MeraStore.Product.Api/Controllers/WeatherForecastController.cs
  src/User/MeraStore.User.Api/Controllers/WeatherForecastController.cs
  src/User/MeraStore.User.Api/MeraStore.User.Api.csproj
  src/User/MeraStore.User.Api/Program.cs
Labels: enhancement, feature
